spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jooq.sql-dialect=POSTGRES
server.servlet.session.timeout=60m


logging.file.name=logs/query-performance.log
logging.level.com.swe481.backend=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n
